try script injection

diff --git a/.github/actions/pending_check/action.yaml b/.github/actions/pending_check/action.yaml
--- a/.github/actions/pending_check/action.yaml
+++ b/.github/actions/pending_check/action.yaml
@@ -37,14 +37,15 @@ runs:
 
 
       function main {
-        if [ "${{ env.PENDING_CHECK }}" == "create" ]; then
+        if [ "${PENDING_CHECK}" == "create" ]; then
           check_create
-        elif [ "${{ env.PENDING_CHECK }}" == "verify" ]; then
-          check_verify
-        else
-          echo "ERROR: invalid action ${{ env.PENDING_CHECK }} for pending check. Allowed: create or verify"
-          exit 1
         fi
+        # elif [ "${{ env.PENDING_CHECK }}" == "verify" ]; then
+        #   check_verify
+        # else
+        #   echo "ERROR: invalid action ${{ env.PENDING_CHECK }} for pending check. Allowed: create or verify"
+        #   exit 1
+        # fi
       }
 
       #---------------------------------------------------------------------------------------------------------------------------------------------------------------------
