set back to a working commit

diff --git a/.github/actions/pending_check/action.yaml b/.github/actions/pending_check/action.yaml
--- a/.github/actions/pending_check/action.yaml
+++ b/.github/actions/pending_check/action.yaml
@@ -39,13 +39,12 @@ runs:
       function main {
         if [ "${PENDING_CHECK}" == "create" ]; then
           check_create
+        elif [ "$PENDING_CHECK" == "verify" ]; then
+          check_verify
+        else
+          echo "ERROR: invalid action ${PENDING_CHECK} for pending check. Allowed: create or verify"
+          exit 1
         fi
-        # elif [ "${{ env.PENDING_CHECK }}" == "verify" ]; then
-        #   check_verify
-        # else
-        #   echo "ERROR: invalid action ${{ env.PENDING_CHECK }} for pending check. Allowed: create or verify"
-        #   exit 1
-        # fi
       }
 
       #---------------------------------------------------------------------------------------------------------------------------------------------------------------------
