move inline bash script to file

diff --git a/.github/actions/pending_check-create/action.yaml b/.github/actions/pending_check-create/action.yaml
--- a/.github/actions/pending_check-create/action.yaml
+++ b/.github/actions/pending_check-create/action.yaml
@@ -12,41 +12,41 @@ runs:
       GITHUB_TOKEN: "${{ github.token }}"
       GITHUB_REPOSITORY: "${{ github.repository }}"
       WORKFLOW_NAME: "${{ github.workflow }}"
-    run: |
-      # Checking run under ACT with override option
-      eval "${ACT_RUN}"
+    run: "${{ github.action_path }}/pending_check.sh"
+      # # Checking run under ACT with override option
+      # eval "${ACT_RUN}"
 
-      echo '::group::Creating new check'
-      curl -vf -POST \
-        --retry 5 \
-        -H "Accept: application/vnd.github+json" \
-        -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
-        "https://api.github.com/repos/${{ env.GITHUB_REPOSITORY }}/check-runs" \
-        -d '
-          {
-            "name":        "${{env.check_name}}",
-            "head_sha":    "${{env.PR_SHA}}",
-            "status":      "in_progress",
-            "external_id": "${{env.GH_RUN_ID}}",
-            "output": {
-                        "title":   "${{ env.WORKFLOW_NAME }} running",
-                        "summary": "pending check for commit ${{env.PR_SHA}}",
-                        "text":    "Awaiting check result..."
-            }
-          }
-        ' \
-        -o new_check.json
+      # echo '::group::Creating new check'
+      # curl -vf -POST \
+      #   --retry 5 \
+      #   -H "Accept: application/vnd.github+json" \
+      #   -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
+      #   "https://api.github.com/repos/${{ env.GITHUB_REPOSITORY }}/check-runs" \
+      #   -d '
+      #     {
+      #       "name":        "${{env.check_name}}",
+      #       "head_sha":    "${{env.PR_SHA}}",
+      #       "status":      "in_progress",
+      #       "external_id": "${{env.GH_RUN_ID}}",
+      #       "output": {
+      #                   "title":   "${{ env.WORKFLOW_NAME }} running",
+      #                   "summary": "pending check for commit ${{env.PR_SHA}}",
+      #                   "text":    "Awaiting check result..."
+      #       }
+      #     }
+      #   ' \
+      #   -o new_check.json
 
-      id=$(jq -r '.id' new_check.json)
+      # id=$(jq -r '.id' new_check.json)
 
-      if [ -z "${id}" ]; then
-        echo "ERROR: Failed to create the required check job"
-        echo "Result of curl:"
-        cat new_check.json
-        exit 1
-      fi
-      echo "::endgroup::"
+      # if [ -z "${id}" ]; then
+      #   echo "ERROR: Failed to create the required check job"
+      #   echo "Result of curl:"
+      #   cat new_check.json
+      #   exit 1
+      # fi
+      # echo "::endgroup::"
 
-      echo "Id is: ${id}"
+      # echo "Id is: ${id}"
 
 
