Used NPM utils in APIServer, ports modified

diff --git a/packages/apiserver/pre_packaging b/packages/apiserver/pre_packaging
--- a/packages/apiserver/pre_packaging
+++ b/packages/apiserver/pre_packaging
@@ -1,32 +1,13 @@
-set -x
+set -e -x
 
-cd ${BUILD_DIR}
+source common/pre-packaging-helper.sh
 
-# Make sure we can see uname
-export PATH=$PATH:/bin:/usr/bin
+# Setup NPM
+setup_npm
 
-#unpack Nodejs - we support Mac OS 64bit and Linux 64bit
-if [ `uname` = "Darwin" ]; then
-  mkdir npm
-  pushd npm
-  tar xvf ../nodejs/node-v6.9.2-darwin-x64.tar.gz --strip-components=1
-elif [ `uname` = "Linux" ]; then
-  mkdir npm
-  pushd npm
-  tar xvf ../nodejs/node-v6.9.2-linux-x64.tar.xz --strip-components=1
-else
-   echo "Not suppored OS (non Linux/Darwin based)"
-fi
+cd ${BUILD_DIR}/app-autoscaler/api && npm install
 
-popd
-
-export PATH=${BUILD_DIR}/npm/bin:$PATH
-cd app-autoscaler/api && npm install --production
-
-#clean build data
-cd ${BUILD_DIR}
-rm -rf npm
-rm -rf nodejs/
-
-
+# Clean up NPM
+rm -rf common/pre-packaging-helper.sh
+cleanup_npm
 
