Fixed shellcheck warnings

diff --git a/jobs/scheduler/templates/install_crt_truststore.erb b/jobs/scheduler/templates/install_crt_truststore.erb
--- a/jobs/scheduler/templates/install_crt_truststore.erb
+++ b/jobs/scheduler/templates/install_crt_truststore.erb
@@ -3,7 +3,7 @@
 
 ## BEGIN CERTIFICATE INSTALLATION
 #define JDK_HOME
-JDK_HOME=/var/vcap/packages/openjdk-11
+export JDK_HOME=/var/vcap/packages/openjdk-11
 
 CERT_ALIAS=$1
 CERT=$2
@@ -18,7 +18,7 @@ TRUST_STORE_FILE=/var/vcap/data/certs/$CERT_ALIAS/cacerts
 PASSWORD=123456
 
 #create directory for trust store
-mkdir -p /var/vcap/data/certs/$CERT_ALIAS
+mkdir -p "/var/vcap/data/certs/$CERT_ALIAS"
 
 #file prefix for the split
 FILE_PREFIX_SPLIT=cert_
@@ -26,60 +26,59 @@ FILE_PREFIX_SPLIT=cert_
 manage_truststore () {
     operation=$1
     
-    NUMBER_OF_CERTS=$(grep 'END CERTIFICATE' $CERT_FILE| wc -l)
+    NUMBER_OF_CERTS=$(grep -c 'END CERTIFICATE' "${CERT_FILE}")
 
   # extract the certificate chain file is split into multiple files
-    csplit $CERT_FILE '/-----END CERTIFICATE-----/1' -f $FILE_PREFIX_SPLIT -q
+    csplit "${CERT_FILE}" '/-----END CERTIFICATE-----/1' -f "${FILE_PREFIX_SPLIT}" -q
   
   # loop over the files to put the certificates in the store
-    for ((i=$NUMBER_OF_CERTS-1; i>=0;i--)) 
-        do
-          ALIAS="$CERT_ALIAS$i"
-          if [ $i -eq 0 ]; then               
-              ALIAS=$CERT_ALIAS
-          fi
+    for ((i=NUMBER_OF_CERTS-1; i>=0;i--))
+    do
+      ALIAS="$CERT_ALIAS$i"
+      if [ $i -eq 0 ]; then
+          ALIAS=$CERT_ALIAS
+      fi
 
-        # echo "keytool -$operation -file "${FILE_PREFIX_SPLIT}0$i" -keystore $TRUST_STORE_FILE -storeType pkcs12 -storepass $PASSWORD -noprompt -alias $ALIAS"
-          keytool -$operation -file "${FILE_PREFIX_SPLIT}0$i" -keystore $TRUST_STORE_FILE -storeType pkcs12 -storepass $PASSWORD -noprompt -alias $ALIAS >/dev/null 2>&1
-        done
+      # echo "keytool -$operation -file "${FILE_PREFIX_SPLIT}0$i" -keystore $TRUST_STORE_FILE -storeType pkcs12 -storepass $PASSWORD -noprompt -alias $ALIAS"
+      keytool "-${operation}" -file "${FILE_PREFIX_SPLIT}0$i" -keystore "${TRUST_STORE_FILE}" -storeType pkcs12 -storepass "${PASSWORD}" -noprompt -alias "${ALIAS}" >/dev/null 2>&1
+    done
 }
 
 #check if the cert file exists, readable and that the trust store exists and is writeable
-if test -r "$CERT_FILE" -a -f "$CERT_FILE"
+if test -r "${CERT_FILE}" -a -f "${CERT_FILE}"
 then
-  if test -f $TRUST_STORE_FILE -a -w $TRUST_STORE_FILE
+  if test -f "${TRUST_STORE_FILE}" -a -w "${TRUST_STORE_FILE}"
   then
     #check to see if the alias exists
-    manage_truststore list
-    if [ $? != 0 ]; then
-      echo "Installing $CERT_FILE with alias $CERT_ALIAS"
-      manage_truststore importcert
-      if [ $? != 0 ]; then
+    if ! manage_truststore list; then
+      echo "Installing ${CERT_FILE} with alias ${CERT_ALIAS}"
+
+      if ! manage_truststore importcert; then
         # implement import error logic
         echo "Failed to install certificate[1]."
       fi
     else
       echo "Certificate already installed. Replacing it"
-      manage_truststore delete
-      if [ $? != 0 ]; then
+
+      if ! manage_truststore delete; then
         # implement import error logic
         echo "Failed to delete existing alias, will attempt to reinstall it"
       fi
-      manage_truststore importcert
-      if [ $? != 0 ]; then
+
+      if ! manage_truststore importcert; then
         # implement import error logic
         echo "Failed to install certificate[2]."
       fi
     fi
   else
-    echo "Installing $CERT_FILE with alias $CERT_ALIAS"
-      manage_truststore importcert
-    if [ $? != 0 ]; then
+    echo "Installing ${CERT_FILE} with alias ${CERT_ALIAS}"
+
+    if ! manage_truststore importcert; then
       # implement import error logic
       echo "Failed to install certificate[3]."
     fi
   fi
 else
-  echo "Unable to read certificate file: $CERT_FILE"
+  echo "Unable to read certificate file: ${CERT_FILE}"
 fi
 ## END CERTIFICATE INSTALLATION
