debug: unexpected EOF

diff --git a/.github/actions/pending_check-finalise/action.yaml b/.github/actions/pending_check-finalise/action.yaml
--- a/.github/actions/pending_check-finalise/action.yaml
+++ b/.github/actions/pending_check-finalise/action.yaml
@@ -26,6 +26,19 @@ runs:
       eval ${ACT_RUN}
       set -euo pipefail
 
+      function send_conclusion() {
+        # https://stackoverflow.com/a/37491820
+      curl -sf -X PATCH \
+          --retry 5 \
+          -H "Accept: application/vnd.github+json" \
+          -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
+          "https://api.github.com/repos/${{ env.GITHUB_REPOSITORY }}/check-runs/${id}" \
+          -d @- << END;
+      { "name": "${{ env.check_name }}", "conclusion": "$1" }
+      END
+      }
+
+
       echo "::group::Getting the latest checks results"
       echo "Getting the last result"
       curl -sf  -H "Accept: application/vnd.github+json" \
@@ -35,9 +48,7 @@ runs:
         | jq '[.check_runs[] | select(.name=="${{ env.check_name }}")]' > results.json
       jq '.|last' results.json > latest_result.json
 
-      check_suite=$( jq '.check_suite.id' latest_result.json )
       id=$( jq '.id' latest_result.json )
-      conclusion=$( jq -r '.conclusion' latest_result.json )
       number_of_checks=$(jq '. | length' results.json)
 
       echo "== Latest ${{env.check_name}} check result =="
@@ -48,7 +59,6 @@ runs:
       echo "::group::Check Info"
       echo "Latest check id:${id}"
       echo "Number of checks for commit ${{ env.PR_SHA }} ${number_of_checks}"
-      echo "Conclusion of check: ${conclusion}"
       echo "::endgroup::"
 
       if [ ${number_of_checks} -eq 0 ]; then
@@ -64,38 +74,58 @@ runs:
 
       if [ -s bad_jobs.txt ]; then
         echo "::group::Sending failed conclusion to the workflow check"
-          curl -sf -X PATCH \
-            --retry 5 \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
-            "https://api.github.com/repos/${{ env.GITHUB_REPOSITORY }}/check-runs/${id}" \
-            -d '
-              {
-                "name": "${{ env.check_name }}",
-                "conclusion": "failure"
-              }
-            '
 
-        echo "ERROR: List of the failed checks:"
         echo "=========================="
+        echo "List of the failed checks:"
         cat bad_jobs.txt
         echo "=========================="
+        echo "::endgroup::"
         exit 1
-
       else
-
         echo "::group::Sending success conclusion to the workflow check"
-          curl -sf -X PATCH \
-            --retry 5 \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
-            "https://api.github.com/repos/${{ env.GITHUB_REPOSITORY }}/check-runs/${id}" \
-            -d '
-              {
-                "name": "${{ env.check_name }}",
-                "conclusion": "success"
-              }
-            ' > /dev/null
+        echo "::endgroup::"
       fi
-      echo "::endgroup::
+
+#      if [ -s bad_jobs.txt ]; then
+#        echo "::group::Sending failed conclusion to the workflow check"
+#
+#        echo "ERROR: List of the failed checks:"
+#        echo "=========================="
+#        cat bad_jobs.txt
+#        echo "::endgroup::=========================="
+#       exit 1
+#
+#      else
+#         echo "::group::Sending success conclusion to the workflow check"
+#
+#         echo "::endgroup::
+#      fi
+
+
+# if [ -s bad_jobs.txt ]; then
+#    echo "::group::Sending failed conclusion to the workflow check"
+#      curl -sf -X PATCH \
+#        --retry 5 \
+#        -H "Accept: application/vnd.github+json" \
+#        -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
+#        "https://api.github.com/repos/${{ env.GITHUB_REPOSITORY }}/check-runs/${id}" \
+#        -d '{ "name": "${{ env.check_name }}", "conclusion": "failure" }'
+
+#   echo "ERROR: List of the failed checks:"
+#   echo "=========================="
+#   cat bad_jobs.txt
+#   echo "=========================="
+#   exit 1
+
+# else
+
+#   echo "::group::Sending success conclusion to the workflow check"
+#     curl -sf -X PATCH \
+#       --retry 5 \
+#       -H "Accept: application/vnd.github+json" \
+#       -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
+#       "https://api.github.com/repos/${{ env.GITHUB_REPOSITORY }}/check-runs/${id}" \
+#       -d '{ "name": "${{ env.check_name }}", "conclusion": "success" }' > /dev/null
+# fi
+# echo "::endgroup::
 
