Added mvn version check and cleaned up BUILD_DIR

diff --git a/packages/db/pre_packaging b/packages/db/pre_packaging
--- a/packages/db/pre_packaging
+++ b/packages/db/pre_packaging
@@ -9,12 +9,12 @@ export PATH=$PATH:/bin:/usr/bin
 if [ `uname` = "Darwin" ]; then
   mkdir java
   pushd java
-  tar zxvf ${RELEASE_DIR}/blobs/openjdk/openjdk-1.8.0_101-x86_64-mountainlion.tar.gz
+  tar zxvf ../openjdk/openjdk-1.8.0_101-x86_64-mountainlion.tar.gz
   export JAVA_HOME=${BUILD_DIR}/java
 elif [ `uname` = "Linux" ]; then
   mkdir java
   pushd java
-  tar zxvf ${RELEASE_DIR}/blobs/openjdk/openjdk-1.8.0_101-x86_64-trusty.tar.gz
+  tar zxvf ../openjdk/openjdk-1.8.0_101-x86_64-trusty.tar.gz
   export JAVA_HOME=${BUILD_DIR}/java
 else
   if [ ! -d $JAVA_HOME ]; then
@@ -28,29 +28,34 @@ popd
 export PATH=$JAVA_HOME/bin:$PATH
 
 # Set up Maven
+function version { echo "$@" | awk -F. '{ printf("%02d%02d%02d\n", $1,$2,$3); }'; }
 which mvn
-if [[ $? != 0 ]]; then
-   echo "Maven Not installed! Installing ..."
-   if [ -f apache-maven-3.3.9-bin.tar.gz ] ; then
-     echo "Maven binary already exists"
-   else
-     echo "Downloading Maven binary"
-     wget -c http://mirror.ventraip.net.au/apache/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
-   fi
-   mkdir maven
-   pushd maven
-   tar zxvf ../apache-maven-3.3.9-bin.tar.gz
-   export M2_HOME=${BUILD_DIR}/maven/apache-maven-3.3.9
-   export PATH=$M2_HOME/bin:$PATH
-   popd
+exit_code=$?
+# Get the current maven version
+if [[ $exit_code -eq 0 ]]; then
+  mvn_version=`mvn -v | grep Apache | awk '{print $3}'`
+fi
+if [[ $exit_code -eq 0 && "$(version "$mvn_version")" -gt "$(version "3.3.1")" ]] ; then
+  echo "Supported maven version is already installed."
 else
-   echo "Maven already installed"
+  echo "Required version of maven not installed! Installing ..."
+  wget -c http://mirror.ventraip.net.au/apache/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
+  mkdir maven
+  pushd maven
+  tar zxvf ../apache-maven-3.3.9-bin.tar.gz
+  export M2_HOME=${BUILD_DIR}/maven/apache-maven-3.3.9
+  export PATH=$M2_HOME/bin:$PATH
+  popd
 fi
 
-cd ${RELEASE_DIR}/src/app-autoscaler/db && mvn package
-cp -R ${RELEASE_DIR}/src/app-autoscaler/db/target/ ${BUILD_DIR}/
-rm -rf ${RELEASE_DIR}/src/app-autoscaler/db/target/
+# Packaging DB module
+cd app-autoscaler/db && mvn package
 
-
-
-
+#clean up build data
+cd ${BUILD_DIR}
+rm -rf java
+rm -rf openjdk/
+if [ -f apache-maven-3.3.9-bin.tar.gz ] ; then
+  rm -rf apache-maven-3.3.9-bin.tar.gz
+  rm -rf maven/
+fi
