Bump github.com/golangci/golangci-lint in /src/autoscaler (#751)
Bumps [github.com/golangci/golangci-lint](https://github.com/golangci/golangci-lint) from 1.46.2 to 1.47.1.
- [Release notes](https://github.com/golangci/golangci-lint/releases)
- [Changelog](https://github.com/golangci/golangci-lint/blob/master/CHANGELOG.md)
- [Commits](https://github.com/golangci/golangci-lint/compare/v1.46.2...v1.47.1)

---
updated-dependencies:
- dependency-name: github.com/golangci/golangci-lint
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

diff --git a/.github/workflows/acceptance_tests.yaml b/.github/workflows/acceptance_tests.yaml
--- a/.github/workflows/acceptance_tests.yaml
+++ b/.github/workflows/acceptance_tests.yaml
@@ -40,12 +40,26 @@ jobs:
     steps:
       - run: echo "sha is ${{github.event.pull_request.head.sha}}"
       - run: |
-          id=$(curl -sf -X POST \
-          -H "Accept: application/vnd.github+json" \
-          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-          "https://api.github.com/repos/${GITHUB_REPOSITORY}/check-runs" \
-          -d '{ "name": "${{env.check_name}}","head_sha": "${{ github.event.pull_request.head.sha }}","status": "in_progress","external_id": "${{ github.run_id }}","output":{ "title":"Acceptance Test running", "summary":"acceptance tests for commit ${{ github.event.pull_request.head.sha }}","text":"some text" }}' \
-              | jq '.id')
+          echo "::group::Creating new check"
+          
+          curl -vf -X POST \
+            --retry 5 \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            "https://api.github.com/repos/${GITHUB_REPOSITORY}/check-runs" \
+            -d '{ "name": "${{env.check_name}}","head_sha": "${{ github.event.pull_request.head.sha }}","status": "in_progress","external_id": "${{ github.run_id }}","output":{ "title":"Acceptance Test running", "summary":"acceptance tests for commit ${{ github.event.pull_request.head.sha }}","text":"some text" }}' \
+            -o new_check.json
+            
+          id=$(jq -r '.id' new_check.json)
+  
+          if [ -z "${id}" ]; then
+            echo "ERROR: Failed to create the required check job"
+            echo "Result of curl:"
+            cat new_check.json
+            exit 1
+          fi
+          echo "::endgroup::"
+          
           echo "Id is: ${id}"
           echo "::set-output name=check_id::${id}"
         id: create_check
@@ -100,7 +114,6 @@ jobs:
           ${CI_DIR}/autoscaler/scripts/run-acceptance-tests.sh
 
   acceptance_test_app:
-    # TODO: allow parallel tests run once we have resources available
     needs: [ deploy_autoscaler ]
     name: "APP acceptance tests"
     runs-on: ubuntu-latest
@@ -142,10 +155,11 @@ jobs:
     steps:
       - run: |
           curl -sf -X PATCH \
-          -H "Accept: application/vnd.github+json" \
-          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-          "https://api.github.com/repos/${GITHUB_REPOSITORY}/check-runs/${{needs.start_pending_result.outputs.check_id}}" \
-          -d '{ "name": "${{env.check_name}}", "status": "completed", "conclusion": "success" }'
+            --retry 5 \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            "https://api.github.com/repos/${GITHUB_REPOSITORY}/check-runs/${{needs.start_pending_result.outputs.check_id}}" \
+            -d '{ "name": "${{env.check_name}}", "status": "completed", "conclusion": "success" }'
 
   deployment_cleanup:
     needs: [ completed_run ]
@@ -169,9 +183,10 @@ jobs:
       - name: Retrieve and assume last acceptance test result
         run: |
           echo "::group::Getting the latest acceptance test result"
-          set -e
+          set -eo pipefail
           echo "Getting the last result"
           curl -sf  -H "Accept: application/vnd.github+json" \
+            --retry 5 \
             -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             "https://api.github.com/repos/${GITHUB_REPOSITORY}/commits/${{ github.event.pull_request.head.sha }}/check-runs" \
             | jq '[.check_runs[] | select(.name=="${{env.check_name}}")]' > results.json
@@ -202,7 +217,7 @@ jobs:
             echo 
             echo "List of the failed checks:"
             echo "=========================="
-            curl -sf "https://api.github.com/repos/${GITHUB_REPOSITORY}/commits/${{ github.event.pull_request.head.sha }}/check-runs" \
+            curl -sf --retry 5 "https://api.github.com/repos/${GITHUB_REPOSITORY}/commits/${{ github.event.pull_request.head.sha }}/check-runs" \
                 |  jq '.check_runs[] | select(.conclusion == "failure") | select(.name? | match(".*acceptance tests")) | " - \(.name): \(.html_url)"'
             echo "=========================="
             exit 1
