Refactor envelope processor
Adds test cases for envelope processor test suite

Adds diagram modifications for metric server

Update go mod

Updated package specs

diff --git a/.github/workflows/bosh-release-checks.yaml b/.github/workflows/bosh-release-checks.yaml
--- a/.github/workflows/bosh-release-checks.yaml
+++ b/.github/workflows/bosh-release-checks.yaml
@@ -13,20 +13,20 @@ jobs:
       - uses: actions/checkout@v3
       - uses: ./.github/actions/setup_go
 
-      - name: Go Build
+      - name: sync-package-specs
         run: |
           source .envrc
           ./scripts/sync-package-specs
 
-      - name: Check if there are changes
-        id: changes
-        uses: UnicornGlobal/has-changes-action@v1.0.12
-
-      - name: Process changes
-        if: steps.changes.outputs.changed == 1
+      - name: Check if there is any change
         run: |
-          echo "::error::Specs are out of date, run ./scripts/update && ./scripts/sync-package-specs to update"
-          exit 1
+          git config --global --add safe.directory "${{ env.GITHUB_WORKSPACE }}"; \
+            [ $(git status --porcelain | wc -l) -eq 0 ] || \
+            { \
+              git status;\
+              echo "::error::Specs are out of date, run ./scripts/update && ./scripts/sync-package-specs to update";\
+              exit 1;\
+            }
 
   bosh-release:
     needs: generate-gosub
@@ -50,7 +50,6 @@ jobs:
         run: |
           set -e
           export PATH=$PATH:/usr/local/maven/bin
-          echo $PATH
           ./scripts/update
 
       - name: Build Dev Release
