separate download and update java scripts
bring original changes from master

diff --git a/.github/workflows/bosh-release-checks.yaml b/.github/workflows/bosh-release-checks.yaml
--- a/.github/workflows/bosh-release-checks.yaml
+++ b/.github/workflows/bosh-release-checks.yaml
@@ -28,12 +28,12 @@ jobs:
           make package-specs
       - name: Check if there is any change
         run: |
-            [ $(git status --porcelain | wc -l) -eq 0 ] || \
-            { \
-              git status;\
-              echo "::error::Specs are out of date, run \"make package-specs\" to update";\
-              exit 1;\
-            }
+          [ $(git status --porcelain | wc -l) -eq 0 ] || \
+          { \
+            git status;\
+            echo "::error::Specs are out of date, run \"make package-specs\" to update";\
+            exit 1;\
+          }
   bosh-release:
     needs: generate-gosub
     name: Create Bosh Release
@@ -55,7 +55,7 @@ jobs:
           make generate-openapi-generated-clients-and-servers
 
           export PATH="${PATH}:/usr/local/maven/bin"
-          make go-mod-tidy go-mod-vendor db scheduler
+          make go-mod-tidy go-mod-vendor download-java-bosh-package db scheduler
 
       - name: Build Dev Release
         id: build
