try to use bosh

diff --git a/.github/workflows/resume-ci-vms.yml b/.github/workflows/resume-ci-vms.yml
--- a/.github/workflows/resume-ci-vms.yml
+++ b/.github/workflows/resume-ci-vms.yml
@@ -13,23 +13,6 @@ jobs:
     steps:
       - name: checkout app-autoscaler-release
         uses: actions/checkout@v4
-#
-#      - name: auth gcloud
-#        uses: google-github-actions/auth@v2
-#        with:
-#          credentials_json: '${{ secrets.GCP_APP_RUNTIME_INTERFACES_AUTOSCALER_DEPLOYER_KEY }}'
-#
-#      - name: set up gcloud
-#        uses: google-github-actions/setup-gcloud@v2
-#
-#      - name: resume VMs
-#        run: |
-#          gcloud compute instances list --filter="networkInterfaces.network:autoscaler-network" --format="value(name,zone)" --sort-by="~labels.deployment:bosh" | while read -r INSTANCE_NAME ZONE; do
-#            if ! gcloud compute instances resume "$INSTANCE_NAME" --zone="$ZONE" --async; then
-#              echo "failed to initiate resuming $INSTANCE_NAME in $ZONE, continuing with next instance"
-#              continue
-#            fi
-#          done
 
       - name: install devbox
         uses: jetify-com/devbox-install-action@734088efddca47cf44ff8a09289c6d0e51b73218 # v0.12.0
@@ -51,3 +34,21 @@ jobs:
       - name: test bosh command
         run: |
           bosh vms -d cf
+
+#
+#      - name: auth gcloud
+#        uses: google-github-actions/auth@v2
+#        with:
+#          credentials_json: '${{ secrets.GCP_APP_RUNTIME_INTERFACES_AUTOSCALER_DEPLOYER_KEY }}'
+#
+#      - name: set up gcloud
+#        uses: google-github-actions/setup-gcloud@v2
+#
+#      - name: resume VMs
+#        run: |
+#          gcloud compute instances list --filter="networkInterfaces.network:autoscaler-network" --format="value(name,zone)" --sort-by="~labels.deployment:bosh" | while read -r INSTANCE_NAME ZONE; do
+#            if ! gcloud compute instances resume "$INSTANCE_NAME" --zone="$ZONE" --async; then
+#              echo "failed to initiate resuming $INSTANCE_NAME in $ZONE, continuing with next instance"
+#              continue
+#            fi
+#          done
