try to use bosh

diff --git a/.github/workflows/resume-ci-vms.yml b/.github/workflows/resume-ci-vms.yml
--- a/.github/workflows/resume-ci-vms.yml
+++ b/.github/workflows/resume-ci-vms.yml
@@ -9,6 +9,23 @@ jobs:
   resume:
     runs-on: ubuntu-latest
     steps:
+      - name: auth gcloud
+        uses: google-github-actions/auth@v2
+        with:
+          credentials_json: '${{ secrets.GCP_APP_RUNTIME_INTERFACES_AUTOSCALER_DEPLOYER_KEY }}'
+
+      - name: set up gcloud
+        uses: google-github-actions/setup-gcloud@v2
+
+      - name: resume VMs
+        run: |
+          gcloud compute instances list --filter="networkInterfaces.network:autoscaler-network" --format="value(name,zone)" --sort-by="~labels.deployment:bosh" | while read -r INSTANCE_NAME ZONE; do
+            if ! gcloud compute instances resume "$INSTANCE_NAME" --zone="$ZONE" --async; then
+              echo "failed to initiate resuming $INSTANCE_NAME in $ZONE, continuing with next instance"
+              continue
+            fi
+          done
+
       - name: checkout app-autoscaler-release
         uses: actions/checkout@v4
 
@@ -26,30 +43,15 @@ jobs:
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
         with:
           repository: cloudfoundry/app-autoscaler-env-bbl-state
-          ssh-key: ${{ secrets.bbl_ssh_key }}
+          ssh-key: ${{ secrets.BBL_SSH_KEY }}
           path: app-autoscaler-env-bbl-state
 
-      - name: test bosh command
+      - name: login to bosh
         run: |
           pushd "${GITHUB_WORKSPACE}/app-autoscaler-env-bbl-state/bbl-state" > /dev/null
             eval "$(bbl print-env)"
           popd > /dev/null
-          bosh vms -d cf
 
-#
-#      - name: auth gcloud
-#        uses: google-github-actions/auth@v2
-#        with:
-#          credentials_json: '${{ secrets.GCP_APP_RUNTIME_INTERFACES_AUTOSCALER_DEPLOYER_KEY }}'
-#
-#      - name: set up gcloud
-#        uses: google-github-actions/setup-gcloud@v2
-#
-#      - name: resume VMs
-#        run: |
-#          gcloud compute instances list --filter="networkInterfaces.network:autoscaler-network" --format="value(name,zone)" --sort-by="~labels.deployment:bosh" | while read -r INSTANCE_NAME ZONE; do
-#            if ! gcloud compute instances resume "$INSTANCE_NAME" --zone="$ZONE" --async; then
-#              echo "failed to initiate resuming $INSTANCE_NAME in $ZONE, continuing with next instance"
-#              continue
-#            fi
-#          done
+      - name: recreate router VM
+        run: |
+          bosh recreate router -d cf -n
