try to use bosh

diff --git a/.github/workflows/resume-ci-vms.yml b/.github/workflows/resume-ci-vms.yml
--- a/.github/workflows/resume-ci-vms.yml
+++ b/.github/workflows/resume-ci-vms.yml
@@ -9,22 +9,47 @@ jobs:
   resume:
     runs-on: ubuntu-latest
     steps:
-      - name: checkout
+      - name: checkout app-autoscaler-release
         uses: actions/checkout@v4
-
-      - name: auth gcloud
-        uses: google-github-actions/auth@v2
         with:
-          credentials_json: '${{ secrets.GCP_APP_RUNTIME_INTERFACES_AUTOSCALER_DEPLOYER_KEY }}'
+          path: app-autoscaler-release
+#
+#      - name: auth gcloud
+#        uses: google-github-actions/auth@v2
+#        with:
+#          credentials_json: '${{ secrets.GCP_APP_RUNTIME_INTERFACES_AUTOSCALER_DEPLOYER_KEY }}'
+#
+#      - name: set up gcloud
+#        uses: google-github-actions/setup-gcloud@v2
+#
+#      - name: resume VMs
+#        run: |
+#          gcloud compute instances list --filter="networkInterfaces.network:autoscaler-network" --format="value(name,zone)" --sort-by="~labels.deployment:bosh" | while read -r INSTANCE_NAME ZONE; do
+#            if ! gcloud compute instances resume "$INSTANCE_NAME" --zone="$ZONE" --async; then
+#              echo "failed to initiate resuming $INSTANCE_NAME in $ZONE, continuing with next instance"
+#              continue
+#            fi
+#          done
 
-      - name: set up gcloud
-        uses: google-github-actions/setup-gcloud@v2
+      - name: install devbox
+        uses: jetify-com/devbox-install-action@734088efddca47cf44ff8a09289c6d0e51b73218 # v0.12.0
+        with:
+          enable-cache: true
+          project-path: ${{ github.workspace }}/app-autoscaler-release
 
-      - name: resume VMs
+      - name: make devbox shellenv available
         run: |
-          gcloud compute instances list --filter="networkInterfaces.network:autoscaler-network" --format="value(name,zone)" --sort-by="~labels.deployment:bosh" | while read -r INSTANCE_NAME ZONE; do
-            if ! gcloud compute instances resume "$INSTANCE_NAME" --zone="$ZONE" --async; then
-              echo "failed to initiate resuming $INSTANCE_NAME in $ZONE, continuing with next instance"
-              continue
-            fi
-          done
+          cd "${GITHUB_WORKSPACE}/app-autoscaler-release"
+          eval "$(devbox shellenv)"
+          printenv >> "$GITHUB_ENV"
+
+      - name: checkout app-autoscaler-env-bbl-state
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
+        with:
+          repository: cloudfoundry/app-autoscaler-env-bbl-state
+          ssh-key: ${{ secrets.bbl_ssh_key }}
+          path: bbl
+
+      - name: test bosh command
+        run: |
+          bosh vms -d cf
